on:
  push:
    branches-ignore:
      - main
    paths:
      - thys/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Tag
        run: |
          git tag "v${{ github.ref_name }}"
          git push origin ${{ github.ref_name }}

      - name: Create Archives
        run: |
          bash ./.github/scripts/create_archives.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: v${{ github.ref_name }}
          prerelease: false
          files: archives/*.zip
